### ISSUE TITLE
Multi-person action recognition issue

### ISSUE THREAD

**Issue by dvskabangira** [lakpa-tamang9/skeletal_action_recognition#12]
hello,
Thanks for the good work
Am trying to do a demo on multiple people using media-pipe but it only marks points on one person . when i increase the number of persons to two, it brings an error. Is this project supposed to be for a single person?
And instead of recognizing the action, it only displays frames per second. Any solution.  Thanks

**Comment by lakpa-tamang9** [comment]
Hi @dvskabangira at the time of developing this program, Mediapipe only supported single person. You can submit your pr with new multi person pose detection.
